### PR TITLE
Selektion Kontext

### PR DESCRIPTION
**Pull request by juro-ub**
New Field "Kontext"

image

### CODE REVIEW

**Comment by mtrojan-ub** [comment]
Is this basically the same as #149?

**Comment by juro-ub** [comment]
> Is this basically the same as #149?

Yes it is basically the same. This PR will add a Select Field for Kontext and #149 will add a Select Field for "Textkritische Anmerkung"

**Comment by mtrojan-ub** [comment]
Can you please solve the open conflict regarding `updates/24.sql` and update the screenshot so we can see where exactly the field will be? /The new additional field from #149 is not visible yet in the screenshot.)

**Comment by juro-ub** [comment]
> Can you please solve the open conflict regarding `updates/24.sql` and update the screenshot so we can see where exactly the field will be? /The new additional field from #149 is not visible yet in the screenshot.)

Conflicts resolved and screenshot updated

**Pull request merged**
